package com.architecture.gateway.util;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Date;
import java.util.List;

/**
 * Utility class to generate JWT tokens for testing purposes.
 * In production, tokens should be generated by an authentication service.
 */
@Component
public class JwtTokenGenerator {

    @Value("${jwt.secret:your-256-bit-secret-key-for-production-use-a-strong-random-key-at-least-32-characters-long}")
    private String secret;

    @Value("${jwt.expiration:3600000}")
    private Long expiration;

    private SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate a JWT token for testing
     */
    public String generateToken(String username, List<String> roles) {
        return Jwts.builder()
                .subject(username)
                .claim("roles", roles)
                .issuedAt(Date.from(Instant.now()))
                .expiration(Date.from(Instant.now().plusMillis(expiration)))
                .signWith(getSigningKey())
                .compact();
    }

    /**
     * Generate a simple token with just username
     */
    public String generateToken(String username) {
        return generateToken(username, List.of("USER"));
    }
}
